### ISSUE TITLE
Error: No such command "initdb".

### ISSUE THREAD

**Issue by preamptive** [ericmagnuson/rmcontrol#2]
Hi I'm really hoping to get this working but having some issues when I get to....
export FLASK_APP=rmcontrol; python -m flask initdb

I keep getting the Error: No such command "initdb".

I've done a clean install of everything but obviously have missed something.

hope someone can point me in the right direction! cheers Keith

**Comment by preamptive** [comment]
The issue was related to Crypto.Cipher, fixed it by re installing - easy_install pycrypto

**Comment by ericmagnuson** [comment]
Great, glad you got it working!
