### ISSUE TITLE
Python-dev had to be installed

### ISSUE THREAD

**Issue by luketoh** [ericmagnuson/rmcontrol#9]
When executing

pip install pycrypto

there was an error that prevented me from getting pycrypto installed.  Something about 

warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath. src/MD2.c:31:20: fatal error: Python.h: No such file or directory

I searched the net for a reason why and it was suggested that I had to install Python-dev

sudo apt-get install python-dev

after that, I ran pip install pycrypto again and it worked.

**Comment by ericmagnuson** [comment]
Great to know!  Thanks for providing this info.  I will update the readme accordingly.
